title: Dzmitry Litmanovich | Full Stack Developer
description: Full Stack Developer with 5+ years of experience. Ruby, Python, JavaScript.
url: https://dmitrylitmanovich.github.io
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
